typography_spectrum: 0.7309344
color:
  brandColors:
    - '#28271F'
    - '#F0F2FF'
    - '#A39153'
    - '#2066B2'
    - '#94D7FF'
  brandStrength: 0.8308671
  lightness: 0.8426423
  saturation: 0.5741138
  rhythmicContrast: 0.4915176
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6165
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7da3729a-32b2-4216-bb7d-d3e371497a43.jpg
name: The Grand White
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose:
  - type: external
    url: 'http://grandwhitedinner.nutickets.co.za'
    label: Tickets
